export default defineEventHandler(() => {
  return [
    {
      id: 368994681,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNjg5OTQ2ODE=',
      name: 'ArtGalleryProject',
      full_name: 'KodeAndre/ArtGalleryProject',
      private: false,
      html_url: 'https://github.com/KodeAndre/ArtGalleryProject',
      description: 'The not-react version of a portfolio i did for an artist',
      homepage: '',
      size: 7848,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'HTML',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 382719464,
      node_id: 'MDEwOlJlcG9zaXRvcnkzODI3MTk0NjQ=',
      name: 'artgalleryreact',
      full_name: 'KodeAndre/artgalleryreact',
      private: false,
      html_url: 'https://github.com/KodeAndre/artgalleryreact',
      description: 'Portfolio for artist Immu.jpg',
      homepage: 'https://kodeandre.github.io/artgalleryreact/',
      size: 12356,
      stargazers_count: 1,
      watchers_count: 1,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 1,
      default_branch: 'main',
    },
    {
      id: 372785066,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzI3ODUwNjY=',
      name: 'Blackjack',
      full_name: 'KodeAndre/Blackjack',
      private: false,
      html_url: 'https://github.com/KodeAndre/Blackjack',
      description: 'A simple game of Blackjack',
      homepage: '',
      size: 867,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 431918161,
      node_id: 'R_kgDOGb6MUQ',
      name: 'Chatter',
      full_name: 'KodeAndre/Chatter',
      private: false,
      html_url: 'https://github.com/KodeAndre/Chatter',
      description: '(LAN) Chat app made with Typescript and nodejs',
      homepage: 'https://chatter-beryl.vercel.app/',
      size: 203,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 399093442,
      node_id: 'MDEwOlJlcG9zaXRvcnkzOTkwOTM0NDI=',
      name: 'componentcreation',
      full_name: 'KodeAndre/componentcreation',
      private: false,
      html_url: 'https://github.com/KodeAndre/componentcreation',
      description: 'Components for various things',
      homepage: '',
      size: 510,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 394243727,
      node_id: 'MDEwOlJlcG9zaXRvcnkzOTQyNDM3Mjc=',
      name: 'CountdownTimer',
      full_name: 'KodeAndre/CountdownTimer',
      private: false,
      html_url: 'https://github.com/KodeAndre/CountdownTimer',
      description: 'Countdown timer from FrontEnd Mentor',
      homepage: 'https://kodeandre.github.io/CountdownTimer/',
      size: 86,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'CSS',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 377811928,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzc4MTE5Mjg=',
      name: 'cvreact',
      full_name: 'KodeAndre/cvreact',
      private: false,
      html_url: 'https://github.com/KodeAndre/cvreact',
      description: '(Old) Personal CV Website',
      homepage: 'https://kodeandre.github.io/cvreact/',
      size: 25736,
      stargazers_count: 1,
      watchers_count: 1,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [
        'javascript',
        'portfolio',
        'react',
        'reactjs',
      ],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 1,
      default_branch: 'main',
    },
    {
      id: 490214314,
      node_id: 'R_kgDOHTgTqg',
      name: 'cvnuxt',
      full_name: 'KodeAndre/cvnuxt',
      private: false,
      html_url: 'https://github.com/KodeAndre/cvnuxt',
      description: 'CV website created in Nuxt3 (Vue)',
      homepage: 'cvnuxt.vercel.app',
      size: 407,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      topics: [

      ],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 432317203,
      node_id: 'R_kgDOGcSjEw',
      name: 'deploygram',
      full_name: 'KodeAndre/deploygram',
      private: false,
      html_url: 'https://github.com/KodeAndre/deploygram',
      description: null,
      homepage: null,
      size: 307,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 489400457,
      node_id: 'R_kgDOHSuoiQ',
      name: 'echoBot',
      full_name: 'KodeAndre/echoBot',
      private: false,
      html_url: 'https://github.com/KodeAndre/echoBot',
      description: 'Just a discord bot for my own and friends\' enjoyment',
      homepage: '',
      size: 70,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 412101868,
      node_id: 'R_kgDOGJAs7A',
      name: 'gimpinfo',
      full_name: 'KodeAndre/gimpinfo',
      private: false,
      html_url: 'https://github.com/KodeAndre/gimpinfo',
      description: 'Website to keep track of GIM stats++',
      homepage: 'https://gimpinfo.vercel.app',
      size: 430,
      stargazers_count: 1,
      watchers_count: 1,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'gpl-3.0',
        name: 'GNU General Public License v3.0',
        spdx_id: 'GPL-3.0',
        url: 'https://api.github.com/licenses/gpl-3.0',
        node_id: 'MDc6TGljZW5zZTk=',
      },
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 1,
      default_branch: 'main',
    },
    {
      id: 466538748,
      node_id: 'R_kgDOG87Q_A',
      name: 'IdleWeeb',
      full_name: 'KodeAndre/IdleWeeb',
      private: false,
      html_url: 'https://github.com/KodeAndre/IdleWeeb',
      description: 'In no way will this be a good looking game, but it works',
      homepage: '',
      size: 63794,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'C#',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 402143146,
      node_id: 'MDEwOlJlcG9zaXRvcnk0MDIxNDMxNDY=',
      name: 'kodeandre.github.io',
      full_name: 'KodeAndre/kodeandre.github.io',
      private: false,
      html_url: 'https://github.com/KodeAndre/kodeandre.github.io',
      description: 'API for personal jsons',
      homepage: '',
      size: 3,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 405886499,
      node_id: 'MDEwOlJlcG9zaXRvcnk0MDU4ODY0OTk=',
      name: 'mern',
      full_name: 'KodeAndre/mern',
      private: false,
      html_url: 'https://github.com/KodeAndre/mern',
      description: 'My first MERN Project, following MongoDB\'s tutorial',
      homepage: '',
      size: 2399,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 430832933,
      node_id: 'R_kgDOGa39JQ',
      name: 'my-portfolio',
      full_name: 'KodeAndre/my-portfolio',
      private: false,
      html_url: 'https://github.com/KodeAndre/my-portfolio',
      description: 'Portfolio',
      homepage: '',
      size: 13257,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 394540098,
      node_id: 'MDEwOlJlcG9zaXRvcnkzOTQ1NDAwOTg=',
      name: 'NativeTest',
      full_name: 'KodeAndre/NativeTest',
      private: false,
      html_url: 'https://github.com/KodeAndre/NativeTest',
      description: 'React Native Test app',
      homepage: '',
      size: 240,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 381302874,
      node_id: 'MDEwOlJlcG9zaXRvcnkzODEzMDI4NzQ=',
      name: 'react_graph_ql_scrimba',
      full_name: 'KodeAndre/react_graph_ql_scrimba',
      private: false,
      html_url: 'https://github.com/KodeAndre/react_graph_ql_scrimba',
      description: 'Despite the name, this is a pokèdex',
      homepage: '',
      size: 606,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'HTML',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 370944582,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzA5NDQ1ODI=',
      name: 'TaskCafe',
      full_name: 'KodeAndre/TaskCafe',
      private: false,
      html_url: 'https://github.com/KodeAndre/TaskCafe',
      description: 'Cafè website with a map and darkmode menu switching',
      homepage: '',
      size: 3152,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'HTML',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 391157289,
      node_id: 'MDEwOlJlcG9zaXRvcnkzOTExNTcyODk=',
      name: 'visit_southampton',
      full_name: 'KodeAndre/visit_southampton',
      private: false,
      html_url: 'https://github.com/KodeAndre/visit_southampton',
      description: 'Visit Southampton, but not official',
      homepage: 'https://kodeandre.github.io/visit_southampton/',
      size: 142880,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 489791783,
      node_id: 'R_kgDOHTGhJw',
      name: 'vuetorial',
      full_name: 'KodeAndre/vuetorial',
      private: false,
      html_url: 'https://github.com/KodeAndre/vuetorial',
      description: 'Just to learn Vue basics',
      homepage: '',
      size: 75,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Vue',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 487958088,
      node_id: 'R_kgDOHRWmSA',
      name: 'weatherCLI',
      full_name: 'KodeAndre/weatherCLI',
      private: false,
      html_url: 'https://github.com/KodeAndre/weatherCLI',
      description: 'Project to fetch weather data for user chosen city with Bash shell scripting',
      homepage: '',
      size: 8,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Shell',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 424335410,
      node_id: 'R_kgDOGUrYMg',
      name: 'Website_Client_Template',
      full_name: 'KodeAndre/Website_Client_Template',
      private: false,
      html_url: 'https://github.com/KodeAndre/Website_Client_Template',
      description: 'ElectronJS template for websites.',
      homepage: '',
      size: 22,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: true,
      topics: [
        'electronjs',
        'typescript',
      ],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
  ];
});
